### ISSUE TITLE
Faraday 2.0 requirement may result in dependency resolution issues

### ISSUE THREAD

**Issue by itstheraj** [drnic/groq-ruby#15]
Hi folks,

Currently in the gemspec here:

https://github.com/drnic/groq-ruby/blob/47a6dfc9ac5b373a8eaa32235f5e54338a99bda7/groq.gemspec#L36C3-L36C42
```
  spec.add_dependency "faraday", "~> 2.0"
```

It seems that Faraday > 2.0 is required. Is this a hard requirement or will the client still function as expected if versions "~> 1.0" are allowed?

I inquire because there are situations where upgrading this dependency is hard to do, such as applications integrating with slack-ruby-client extensively; applications that require older versions of elasticsearch due to the licensing split there; and quite a few other cases. The gap between Faraday 1 and 2 was large - for applications depending on any ecosystem of the prior it could make it harder to use groq-ruby when it specifies the newer version.

It looks like from the core client here also that there are lighter HTTP client substitutes you could use just as easily? If you all are open to it I am happy to contribute a suggested improvement - but I thought I'd inquire if Faraday 2.0 was a hard requirement before embarking on that.

Cheers - thank you for your time!

**Comment by drnic** [comment]
Are you interested in exploring a PR where the version is more flexible to allow 1.X + 2.X faraday?

**Comment by drnic** [comment]
Ugh, you did and I didn't read all my emails first :)

**Comment by drnic** [comment]
Resolved, thanks.
